name=Adafruit Monster Eyes
version=2.0.0
author=Adafruit Industries
maintainer=Adafruit Industries
sentence=Animated monster eyes for RP2040/RP2350 and ESP32, on SPI TFT, PicoDVI or parallel RGB666 displays.
category=Display
url=https://github.com/adafruit/Adafruit_Monster_Eyes
architectures=rp2040,esp32
depends=Adafruit GFX Library, Adafruit BusIO, Adafruit ST7735 and ST7789 Library, Adafruit ILI9341, Adafruit GC9A01A, PicoDVI - Adafruit Fork, GFX Library for Arduino, Adafruit SPIFlash, SdFat - Adafruit Fork, Adafruit TinyUSB Library, ArduinoJson, Adafruit TSL2585
includes=Adafruit_Monster_Eyes.h
