name=Adafruit Monster Eyes
version=1.0.0
author=Adafruit Industries
maintainer=Adafruit Industries
sentence=Animated monster eyes for RP2040/RP2350 and ESP32, on SPI TFT, PicoDVI or parallel RGB666 displays.
category=Display
url=https://github.com/adafruit/Adafruit_Monster_Eyes
architectures=rp2040,esp32
depends=Adafruit GFX Library, Adafruit BusIO, Adafruit ST7789, Adafruit ILI9341, Adafruit GC9A01A, PicoDVI, GFX Library for Arduino, Adafruit SPIFlash, SdFat - Adafruit Fork, Adafruit TinyUSB Library, ArduinoJson
includes=Adafruit_Monster_Eyes.h
